name: Middleman Build

on:
  push: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: "npm"

      - name: Install Ruby dependencies
        run: bundle install

      - name: Install JS dependencies
        run: npm install

      - name: Build Middleman site
        run: bundle exec middleman build
